//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 8-4-2014 9:44:40
namespace CBSData.OdataCatalog
{
    
    /// <summary>
    /// There are no comments for Catalog in the schema.
    /// </summary>
    public partial class Catalog : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Catalog object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Catalog(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Cbs.OData.Catalog", "CBSData.OdataCatalog");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("CBSData.OdataCatalog", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Cbs.OData.Catalog.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Featured in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Featured> Featured
        {
            get
            {
                if ((this._Featured == null))
                {
                    this._Featured = base.CreateQuery<Featured>("Featured");
                }
                return this._Featured;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Featured> _Featured;
        /// <summary>
        /// There are no comments for Table_Featured in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Table_Featured> Table_Featured
        {
            get
            {
                if ((this._Table_Featured == null))
                {
                    this._Table_Featured = base.CreateQuery<Table_Featured>("Table_Featured");
                }
                return this._Table_Featured;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Table_Featured> _Table_Featured;
        /// <summary>
        /// There are no comments for Tables in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Table> Tables
        {
            get
            {
                if ((this._Tables == null))
                {
                    this._Tables = base.CreateQuery<Table>("Tables");
                }
                return this._Tables;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Table> _Tables;
        /// <summary>
        /// There are no comments for Themes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Theme> Themes
        {
            get
            {
                if ((this._Themes == null))
                {
                    this._Themes = base.CreateQuery<Theme>("Themes");
                }
                return this._Themes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Theme> _Themes;
        /// <summary>
        /// There are no comments for Tables_Themes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Table_Theme> Tables_Themes
        {
            get
            {
                if ((this._Tables_Themes == null))
                {
                    this._Tables_Themes = base.CreateQuery<Table_Theme>("Tables_Themes");
                }
                return this._Tables_Themes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Table_Theme> _Tables_Themes;
        /// <summary>
        /// There are no comments for Featured in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFeatured(Featured featured)
        {
            base.AddObject("Featured", featured);
        }
        /// <summary>
        /// There are no comments for Table_Featured in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTable_Featured(Table_Featured table_Featured)
        {
            base.AddObject("Table_Featured", table_Featured);
        }
        /// <summary>
        /// There are no comments for Tables in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTables(Table table)
        {
            base.AddObject("Tables", table);
        }
        /// <summary>
        /// There are no comments for Themes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToThemes(Theme theme)
        {
            base.AddObject("Themes", theme);
        }
        /// <summary>
        /// There are no comments for Tables_Themes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTables_Themes(Table_Theme table_Theme)
        {
            base.AddObject("Tables_Themes", table_Theme);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"2.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"Cbs.OData.Catalog\" xmlns=\"http://schemas.microsoft.com/ado/2006/04/ed" +
                "m\"><EntityType Name=\"Featured\"><Key><PropertyRef Name=\"ID\" /></Key><Property Nam" +
                "e=\"ID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Number\" Type=\"Edm.Str" +
                "ing\" m:FC_TargetPath=\"SyndicationTitle\" m:FC_ContentKind=\"text\" m:FC_KeepInConte" +
                "nt=\"true\" /><Property Name=\"Title\" Type=\"Edm.String\" m:FC_TargetPath=\"Syndicatio" +
                "nSummary\" m:FC_ContentKind=\"text\" m:FC_KeepInContent=\"true\" /><Property Name=\"De" +
                "scription\" Type=\"Edm.String\" /></EntityType><EntityType Name=\"Table_Featured\"><K" +
                "ey><PropertyRef Name=\"ID\" /></Key><Property Name=\"ID\" Type=\"Edm.Int32\" Nullable=" +
                "\"false\" /><Property Name=\"TableID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property" +
                " Name=\"FeaturedID\" Type=\"Edm.Int32\" Nullable=\"false\" /></EntityType><EntityType " +
                "Name=\"Table\"><Key><PropertyRef Name=\"ID\" /></Key><Property Name=\"ID\" Type=\"Edm.I" +
                "nt32\" Nullable=\"false\" /><Property Name=\"Identifier\" Type=\"Edm.String\" /><Proper" +
                "ty Name=\"Title\" Type=\"Edm.String\" m:FC_TargetPath=\"SyndicationTitle\" m:FC_Conten" +
                "tKind=\"text\" m:FC_KeepInContent=\"true\" /><Property Name=\"ShortTitle\" Type=\"Edm.S" +
                "tring\" /><Property Name=\"Summary\" Type=\"Edm.String\" /><Property Name=\"Modified\" " +
                "Type=\"Edm.DateTime\" m:FC_TargetPath=\"SyndicationUpdated\" m:FC_ContentKind=\"text\"" +
                " m:FC_KeepInContent=\"true\" /><Property Name=\"ReasonDelivery\" Type=\"Edm.String\" /" +
                "><Property Name=\"Language\" Type=\"Edm.String\" /><Property Name=\"Frequency\" Type=\"" +
                "Edm.String\" /><Property Name=\"Period\" Type=\"Edm.String\" /><Property Name=\"Summar" +
                "yAndLinks\" Type=\"Edm.String\" m:FC_TargetPath=\"SyndicationSummary\" m:FC_ContentKi" +
                "nd=\"html\" m:FC_KeepInContent=\"false\" /><Property Name=\"DefaultSettings\" Type=\"Ed" +
                "m.String\" /><Property Name=\"DefaultSelection\" Type=\"Edm.String\" /><NavigationPro" +
                "perty Name=\"Themes\" Relationship=\"Cbs.OData.Catalog.Table_Themes\" ToRole=\"Themes" +
                "\" FromRole=\"Table\" /></EntityType><EntityType Name=\"Theme\"><Key><PropertyRef Nam" +
                "e=\"ID\" /></Key><Property Name=\"ID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property" +
                " Name=\"Number\" Type=\"Edm.String\" m:FC_TargetPath=\"SyndicationTitle\" m:FC_Content" +
                "Kind=\"text\" m:FC_KeepInContent=\"true\" /><Property Name=\"Title\" Type=\"Edm.String\"" +
                " m:FC_TargetPath=\"SyndicationSummary\" m:FC_ContentKind=\"text\" m:FC_KeepInContent" +
                "=\"true\" /></EntityType><EntityType Name=\"Table_Theme\"><Key><PropertyRef Name=\"ID" +
                "\" /></Key><Property Name=\"ID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name" +
                "=\"TableID\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"ThemeID\" Type=\"Ed" +
                "m.Int32\" Nullable=\"false\" /></EntityType><Association Name=\"Table_Themes\"><End T" +
                "ype=\"Cbs.OData.Catalog.Theme\" Role=\"Themes\" Multiplicity=\"*\" /><End Type=\"Cbs.OD" +
                "ata.Catalog.Table\" Role=\"Table\" Multiplicity=\"*\" /></Association><EntityContaine" +
                "r Name=\"Catalog\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"Featured\" En" +
                "tityType=\"Cbs.OData.Catalog.Featured\" /><EntitySet Name=\"Table_Featured\" EntityT" +
                "ype=\"Cbs.OData.Catalog.Table_Featured\" /><EntitySet Name=\"Tables\" EntityType=\"Cb" +
                "s.OData.Catalog.Table\" /><EntitySet Name=\"Themes\" EntityType=\"Cbs.OData.Catalog." +
                "Theme\" /><EntitySet Name=\"Tables_Themes\" EntityType=\"Cbs.OData.Catalog.Table_The" +
                "me\" /><AssociationSet Name=\"Table_Themes\" Association=\"Cbs.OData.Catalog.Table_T" +
                "hemes\"><End Role=\"Table\" EntitySet=\"Tables\" /><End Role=\"Themes\" EntitySet=\"Them" +
                "es\" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></edmx:Edm" +
                "x>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for Cbs.OData.Catalog.Featured in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Featured")]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("Number", global::System.Data.Services.Common.SyndicationItemProperty.Title, global::System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("Title", global::System.Data.Services.Common.SyndicationItemProperty.Summary, global::System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Featured : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Featured object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Featured CreateFeatured(int ID)
        {
            Featured featured = new Featured();
            featured.ID = ID;
            return featured;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this._Number = value;
                this.OnNumberChanged();
                this.OnPropertyChanged("Number");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Number;
        partial void OnNumberChanging(string value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Cbs.OData.Catalog.Table_Featured in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Table_Featured")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Table_Featured : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Table_Featured object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="tableID">Initial value of TableID.</param>
        /// <param name="featuredID">Initial value of FeaturedID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Table_Featured CreateTable_Featured(int ID, int tableID, int featuredID)
        {
            Table_Featured table_Featured = new Table_Featured();
            table_Featured.ID = ID;
            table_Featured.TableID = tableID;
            table_Featured.FeaturedID = featuredID;
            return table_Featured;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property TableID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int TableID
        {
            get
            {
                return this._TableID;
            }
            set
            {
                this.OnTableIDChanging(value);
                this._TableID = value;
                this.OnTableIDChanged();
                this.OnPropertyChanged("TableID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _TableID;
        partial void OnTableIDChanging(int value);
        partial void OnTableIDChanged();
        /// <summary>
        /// There are no comments for Property FeaturedID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int FeaturedID
        {
            get
            {
                return this._FeaturedID;
            }
            set
            {
                this.OnFeaturedIDChanging(value);
                this._FeaturedID = value;
                this.OnFeaturedIDChanged();
                this.OnPropertyChanged("FeaturedID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _FeaturedID;
        partial void OnFeaturedIDChanging(int value);
        partial void OnFeaturedIDChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Cbs.OData.Catalog.Table in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Tables")]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("Title", global::System.Data.Services.Common.SyndicationItemProperty.Title, global::System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("Modified", global::System.Data.Services.Common.SyndicationItemProperty.Updated, global::System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("SummaryAndLinks", global::System.Data.Services.Common.SyndicationItemProperty.Summary, global::System.Data.Services.Common.SyndicationTextContentKind.Html, false)]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Table : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Table object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Table CreateTable(int ID)
        {
            Table table = new Table();
            table.ID = ID;
            return table;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Identifier in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Identifier
        {
            get
            {
                return this._Identifier;
            }
            set
            {
                this.OnIdentifierChanging(value);
                this._Identifier = value;
                this.OnIdentifierChanged();
                this.OnPropertyChanged("Identifier");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Identifier;
        partial void OnIdentifierChanging(string value);
        partial void OnIdentifierChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property ShortTitle in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ShortTitle
        {
            get
            {
                return this._ShortTitle;
            }
            set
            {
                this.OnShortTitleChanging(value);
                this._ShortTitle = value;
                this.OnShortTitleChanged();
                this.OnPropertyChanged("ShortTitle");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ShortTitle;
        partial void OnShortTitleChanging(string value);
        partial void OnShortTitleChanged();
        /// <summary>
        /// There are no comments for Property Summary in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Summary
        {
            get
            {
                return this._Summary;
            }
            set
            {
                this.OnSummaryChanging(value);
                this._Summary = value;
                this.OnSummaryChanged();
                this.OnPropertyChanged("Summary");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Summary;
        partial void OnSummaryChanging(string value);
        partial void OnSummaryChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property ReasonDelivery in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ReasonDelivery
        {
            get
            {
                return this._ReasonDelivery;
            }
            set
            {
                this.OnReasonDeliveryChanging(value);
                this._ReasonDelivery = value;
                this.OnReasonDeliveryChanged();
                this.OnPropertyChanged("ReasonDelivery");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ReasonDelivery;
        partial void OnReasonDeliveryChanging(string value);
        partial void OnReasonDeliveryChanged();
        /// <summary>
        /// There are no comments for Property Language in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Language
        {
            get
            {
                return this._Language;
            }
            set
            {
                this.OnLanguageChanging(value);
                this._Language = value;
                this.OnLanguageChanged();
                this.OnPropertyChanged("Language");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Language;
        partial void OnLanguageChanging(string value);
        partial void OnLanguageChanged();
        /// <summary>
        /// There are no comments for Property Frequency in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Frequency
        {
            get
            {
                return this._Frequency;
            }
            set
            {
                this.OnFrequencyChanging(value);
                this._Frequency = value;
                this.OnFrequencyChanged();
                this.OnPropertyChanged("Frequency");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Frequency;
        partial void OnFrequencyChanging(string value);
        partial void OnFrequencyChanged();
        /// <summary>
        /// There are no comments for Property Period in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Period
        {
            get
            {
                return this._Period;
            }
            set
            {
                this.OnPeriodChanging(value);
                this._Period = value;
                this.OnPeriodChanged();
                this.OnPropertyChanged("Period");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Period;
        partial void OnPeriodChanging(string value);
        partial void OnPeriodChanged();
        /// <summary>
        /// There are no comments for Property SummaryAndLinks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SummaryAndLinks
        {
            get
            {
                return this._SummaryAndLinks;
            }
            set
            {
                this.OnSummaryAndLinksChanging(value);
                this._SummaryAndLinks = value;
                this.OnSummaryAndLinksChanged();
                this.OnPropertyChanged("SummaryAndLinks");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SummaryAndLinks;
        partial void OnSummaryAndLinksChanging(string value);
        partial void OnSummaryAndLinksChanged();
        /// <summary>
        /// There are no comments for Property DefaultSettings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DefaultSettings
        {
            get
            {
                return this._DefaultSettings;
            }
            set
            {
                this.OnDefaultSettingsChanging(value);
                this._DefaultSettings = value;
                this.OnDefaultSettingsChanged();
                this.OnPropertyChanged("DefaultSettings");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DefaultSettings;
        partial void OnDefaultSettingsChanging(string value);
        partial void OnDefaultSettingsChanged();
        /// <summary>
        /// There are no comments for Property DefaultSelection in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DefaultSelection
        {
            get
            {
                return this._DefaultSelection;
            }
            set
            {
                this.OnDefaultSelectionChanging(value);
                this._DefaultSelection = value;
                this.OnDefaultSelectionChanged();
                this.OnPropertyChanged("DefaultSelection");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DefaultSelection;
        partial void OnDefaultSelectionChanging(string value);
        partial void OnDefaultSelectionChanged();
        /// <summary>
        /// There are no comments for Themes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Theme> Themes
        {
            get
            {
                return this._Themes;
            }
            set
            {
                this._Themes = value;
                this.OnPropertyChanged("Themes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Theme> _Themes = new global::System.Data.Services.Client.DataServiceCollection<Theme>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Cbs.OData.Catalog.Theme in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Themes")]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("Number", global::System.Data.Services.Common.SyndicationItemProperty.Title, global::System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]
    [global::System.Data.Services.Common.EntityPropertyMappingAttribute("Title", global::System.Data.Services.Common.SyndicationItemProperty.Summary, global::System.Data.Services.Common.SyndicationTextContentKind.Plaintext, true)]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Theme : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Theme object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Theme CreateTheme(int ID)
        {
            Theme theme = new Theme();
            theme.ID = ID;
            return theme;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this._Number = value;
                this.OnNumberChanged();
                this.OnPropertyChanged("Number");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Number;
        partial void OnNumberChanging(string value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this._Title = value;
                this.OnTitleChanged();
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Cbs.OData.Catalog.Table_Theme in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Tables_Themes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Table_Theme : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Table_Theme object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="tableID">Initial value of TableID.</param>
        /// <param name="themeID">Initial value of ThemeID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Table_Theme CreateTable_Theme(int ID, int tableID, int themeID)
        {
            Table_Theme table_Theme = new Table_Theme();
            table_Theme.ID = ID;
            table_Theme.TableID = tableID;
            table_Theme.ThemeID = themeID;
            return table_Theme;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property TableID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int TableID
        {
            get
            {
                return this._TableID;
            }
            set
            {
                this.OnTableIDChanging(value);
                this._TableID = value;
                this.OnTableIDChanged();
                this.OnPropertyChanged("TableID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _TableID;
        partial void OnTableIDChanging(int value);
        partial void OnTableIDChanged();
        /// <summary>
        /// There are no comments for Property ThemeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ThemeID
        {
            get
            {
                return this._ThemeID;
            }
            set
            {
                this.OnThemeIDChanging(value);
                this._ThemeID = value;
                this.OnThemeIDChanged();
                this.OnPropertyChanged("ThemeID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ThemeID;
        partial void OnThemeIDChanging(int value);
        partial void OnThemeIDChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
